### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by funnynin** [networkMe/missinghud2#11]
Tears tracker causes minor frame drops (new update).

Shot height works fine,

3 decimal places drops about 3fps,

4 decimal places drops about 10-20 fps,

5 decimal places drops about 20 fps.

**Comment by networkMe** [comment]
I have no problem running MHUD2 in a virtual machine, with next to no game support, so that seems extremely weird. Is this occurring on Windows XP or something? What are the computer specs? GPU, CPU?

**Comment by funnynin** [comment]
Windows 10 x64,
AMD II X6 1100T ( http://www.cpubenchmark.net/cpu.php?cpu=AMD+Phenom+II+X6+1100T ),
Not sure about the GPU...

**Comment by networkMe** [comment]
I've honestly had no more reports of this, and I myself can barely get MHUD2 to slow the game by 1-2 FPS, let alone 20 FPS. I'm going to close this for now unless I get more reports of it happening.
