### ISSUE TITLE
Don't stop supporting Rebirth.

### ISSUE THREAD

**Issue by Prezombie** [networkMe/missinghud2#14]
Please, don't just support afterbirth from here on, it's silly to restrict the new versions to just the expansion version.

**Comment by networkMe** [comment]
The thing is; it looks like the game developers themselves are dropping support for Rebirth. It hasn't been updated with any of the Afterbirth balancing changes like the new DWD chance on Book of Belial or the D4 on The Lost. If that stays the way it is, v1.2.4 will never stop working on it.

If I release a new version of MHUD2 with significant features I will likely do a dual-version release. v1.3.0 was very much an Afterbirth support build anyway (unless you really care about Shot Height).

**Comment by Prezombie** [comment]
That's good to hear. Even a manually set option to apply to AB or RB would be decent, it's rather jarring to update, see "For Rebirth + Afterbirth", then have RB crash the moment MHUD tries to join the party, and only then see the notice that the new version isn't actually for AB. :P

**Comment by networkMe** [comment]
v1.4.0 has full Rebirth & Afterbirth support.
