### ISSUE TITLE
Error While Executing LoadLibraryW

### ISSUE THREAD

**Issue by TravisGurlik** [networkMe/missinghud2#17]
I'm not sure if this is an issue with the actual code or if I'm just not doing something right, but every time I run this while Afterbirth is open it throws a LoadLibraryIntoBoI error and recommend running it from a different directory path. I have tried moving the zip folder to just about everywhere, including the same folder isaac-ng is in (C:/Program Files (x86)/Steam/steamapps/common/The Binding of Isaac Rebirth). I am running Windows 8.1 if that matters in this case. If I could get some help with figuring out where to put the files, then that would be greatly appreciated.

**Comment by networkMe** [comment]
If it's not the directory path (which it clearly isn't in your case), then that error signifies something is blocking DLL injection on your computer. Usually an anti-virus or similar.

Running as admin may fix it. Otherwise your going to have to figure out what's blocking it.

**Comment by TravisGurlik** [comment]
Running as admin fixed the LoadLibraryW error, but I got an error with the DLL injection instead when Isaac started. When I get a chance later I will look at my anti-virus software to try and fix this.

**Comment by TravisGurlik** [comment]
Well, after taking the action I should have tried in the first place, I got it to work after setting it as trusted in my anti-virus software. Sorry for the stupid question, but thanks for your help anyways.
