### ISSUE TITLE
Same problem that someone had with 1.2.4, on 1.3.0

### ISSUE THREAD

**Issue by manoftron** [networkMe/missinghud2#18]
Wanted to try missinghud2 when AB came out, but I'm getting this: http://pastebin.com/4cZvaSr4

I'm on Win 7 64, and I'm not too sure about what I'm doing wrong otherwise besides maybe putting it in the wrong folder.

**Comment by networkMe** [comment]
Well, as you said, he had that problem in 1.2.4 and worked out it was CCleaner blocking boost::interprocess from running. If it's not the same program for you, then it's something else on your machine that is having the same effect. That error relates to boost::interprocess being unable to create the "shared memory" file at "%PROGRAMDATA%\boost_interprocess".

**Comment by manoftron** [comment]
I don't use CCleaner but I use Avast, and after adding that to exceptions, I still got the same error.

**Comment by networkMe** [comment]
I honestly can't tell you the exact application on your machine that's causing issue with boost::interprocess library, just that there is one. The boost::interprocess library is a tried and tested library, so I highly doubt it's the code itself that is causing you issues.

**Comment by Vega-ss** [comment]
So, what do you do with this error?

**Comment by D3l3t3m4n** [comment]
Is there any way for the program to figure out what's blocking it? I really like the mod but I have no clue about what's blocking it.

**Comment by networkMe** [comment]
I can't know because it could be way too many things.

However can you try the version I posted in the below issue: 
https://github.com/networkMe/missinghud2/issues/26

It may help at least one of you.

**Comment by D3l3t3m4n** [comment]
It didn't work for me, hope it works for others! I guess I'll have no stat tracker then :P

**Comment by Vega-ss** [comment]
Strange, but MH2 1.2.3 and only Rebirth - works. In 1.4.0 you say you fixed an error,  but the error remains.

**Comment by networkMe** [comment]
Well, the fix I introduced will only help some people (and it has). Your error code can be translated to ERROR_ALREADY_EXISTS which indicates that deleting the "%PROGRAMDATA%\boost_interprocess" directory on your computer could fix your issue...

**Comment by networkMe** [comment]
I'm going to close this as there is nothing more I can do inside MHUD2's codebase to rectify this issue. It really comes down to an incompatibility with boost::interprocess and the users machine, both of which I have little control over.
