### ISSUE TITLE
Minimize to tray option

### ISSUE THREAD

**Issue by squee666** [networkMe/missinghud2#19]
Just a small enhancement since we dont really need it in the taskbar the tray is less intrusive

**Comment by samuelschoe** [comment]
As a workaround, you can make a shortcut for the launcher in windows, go into properties, and select "minimized" in the run option. That will start the program minimized.

**Comment by networkMe** [comment]
I had a look at this for v1.4.0 and I have to say I disliked it in practice. I often had multiple MHUD's running without even realizing it because they were all hidden in the tray. I think it causes too much confusion for such a minor "intrusion" to the window list space.
