### ISSUE TITLE
Devil Deal Percentage Chance Not yet working for XL floors

### ISSUE THREAD

**Issue by 40163650** [networkMe/missinghud2#2]
Here's a picture: http://imgur.com/gallery/0GMoH4Z/new

**Comment by networkMe** [comment]
Is that the latest v1.2.1?
I believe I've fixed the issue with labyrinth floors unless your saying there's  another one.

**Comment by 40163650** [comment]
Ah, I was still on 1.1.0, I didn't realize there was an update, it's fixed.
