### ISSUE TITLE
Error on 1.2.4 and 1.3.1

### ISSUE THREAD

**Issue by TheDehvi** [networkMe/missinghud2#21]
Hey there,

I downloaded the MissingHUD 2 today and on the first try it opened well. 
All the other tries ended up like this and its not CCleaner or the Path
![error](https://cloud.githubusercontent.com/assets/15654643/10943438/b1245a1a-8314-11e5-859a-88b10dbef99e.JPG)
Path:
![path](https://cloud.githubusercontent.com/assets/15654643/10943465/c7b015c6-8314-11e5-95e7-bc245abf1e86.JPG)

as you can see too I downloaded more than one Version 
Im using 
Win 10 and Kaspersky 
also moving the executable into the Isaac Direction havent worked and even deinstalling and reinstalling both Isaac(also to new directions like C:\ or D:\) and MissingHud 

I hope someone of you can help me :/

Thanks

**Comment by networkMe** [comment]
This is most likely an anti-virus related issue. Something on your machine is blocking "CreateRemoteThread" for security reasons.

Try running MHUD2 as admin, or adding the .exe to Kaspersky's exclusions list.

**Comment by TheDehvi** [comment]
thank you very much. I now have fixed the problem but a new error occured.
![new](https://cloud.githubusercontent.com/assets/15654643/10972754/e0192b18-83da-11e5-8d4f-37441cec34dc.JPG)

Its when I run the HUD2 when i am Admin as well.

Sry if its a bit too much but I´m not extremely good with these specific types of errors.

Thanks again

**Comment by TheDehvi** [comment]
Fixed it :D 
.
.
.
Now this D:
![d](https://cloud.githubusercontent.com/assets/15654643/10978280/534260ee-83f6-11e5-91e1-58b5c0e166af.JPG)

**Comment by networkMe** [comment]
You need to look at the MHUD2.log file to work out the exact error the injected DLL is having.

**Comment by networkMe** [comment]
Closed due to inactivity...
