### ISSUE TITLE
Linux support ?

### ISSUE THREAD

**Issue by andrelec1** [networkMe/missinghud2#23]
a linux release scheduled ?

**Comment by networkMe** [comment]
This (along with Mac OSX support) is very unlikely unless someone else wants to take on the job of re-coding the injection & hooking part of the mod. The raw nature of low-level API runtime hooking means you need (completely) different implementations for each OS which I am not really interested in writing or maintaining.

Of course, the GUI and HUD itself are cross-platform (Qt and OpenGL respectively) so forking the current code would give anyone wanting to do this a big head start.
