### ISSUE TITLE
Missing HUD 2 problems with the latest Afterbirth patch

### ISSUE THREAD

**Issue by Skel0t** [networkMe/missinghud2#27]
Good evening,
I just installed the new The Binding of Isaac: Rebirth patch and realized that Missing HUD only shows 0.00 at every stat (except of the devil deal chance). So I don't know if it is a bug with Missing HUD or a problem with my PC.
I'm playing on Windows 10 64bit. My system specs are more than enough to play isaac.

I#m looking forward to getting this fixed :)

**Comment by GuyDuderson** [comment]
Same here, I just installed the mod.
I guess we'll either have to hope that the next patch somehow fixes it, or networkMe fixes it himself.

**Comment by networkMe** [comment]
Hey,

I just released a new version which fixes this!
The Afterbirth developers changed the memory layout of the Player which threw MHUD2 off.

Thanks,
