### ISSUE TITLE
error occurred

### ISSUE THREAD

**Issue by DualWield** [networkMe/missinghud2#28]
[LoadLibraryIntoBoI] Couldn't write the path to MIssingHUD2Hook.dll into the BoI process.

**Comment by DualWield** [comment]
![image](https://cloud.githubusercontent.com/assets/4132470/11167541/0b038d14-8ba1-11e5-94fe-9e6dd43268ab.png)

**Comment by networkMe** [comment]
Can you try the version in this issue?
https://github.com/networkMe/missinghud2/issues/26

I believe it should fix that problem you are having.

**Comment by networkMe** [comment]
Closed due to inactivity...
