### ISSUE TITLE
Tears stat.

### ISSUE THREAD

**Issue by 40163650** [networkMe/missinghud2#3]
It seems when the fire rate increases the displayed stat goes down (to a minimum of 1), if it's the tear delay stat there's a formula for calculating tears from it here (for the original Isaac, I'm not sure if it's the same in rebirth) http://bindingofisaac.wikia.com/wiki/Thread:39512
But according to the wiki it's just the inverse.

**Comment by networkMe** [comment]
It's currently the tear delay stat.

What you're describing is essentially the same stat though, as the tear delay goes down the "tears" stat will go up. I picked the tear delay stat to represent tears on the HUD as it's what Isaac uses in it's internal memory when it shows its stat screen and when it modifies tears (with pills and items). It comes down to a matter of unit preference. 

When Afterbirth comes out I will implement a settings menu which lets you set preferences like this (including moving the HUD also). The reason I'm not going to implement it right now is the Afterbirth team may very well implement their own raw stats option in-game making this project deprecated. I'm not going to invest additional major time into this project until we know one way or the other.
