### ISSUE TITLE
Issue #18 & #24, but in 1.3.2

### ISSUE THREAD

**Issue by Spooted** [networkMe/missinghud2#31]
Yes, I know this is a duplicate issue, but in #24, his screenshot of the MHUD2.log is different than mine. 
![image](https://cloud.githubusercontent.com/assets/15880783/11199759/4115f996-8c96-11e5-9b50-b08fde9f412b.png)
That is what mine looks like, and I see no reference to boost:interprocesscommunication in my file, it is in his file though.

**Comment by networkMe** [comment]
That's because that's not MHUD2.log, that's MHUD2.log.conf.

Can you try the version I posted in this issue (as admin and non-admin):
https://github.com/networkMe/missinghud2/issues/26

It may fix your issue.

**Comment by Spooted** [comment]
The MEGA worked, thanks
