### ISSUE TITLE
OSX Support ?

### ISSUE THREAD

**Issue by Elendir** [networkMe/missinghud2#32]
Hi,

I was just wondering if your are planning in near future to add an OSX support ?
I know it would be much work because you should have to do the injection on dylibs, and I don't even know if it's possible due to the sandbox behavior in OSX.

**Comment by networkMe** [comment]
Please see:
https://github.com/networkMe/missinghud2/issues/23

**Comment by Elendir** [comment]
Sorry didn't see this was already asked.
