### ISSUE TITLE
Request: Add batch options.

### ISSUE THREAD

**Issue by eodeth** [networkMe/missinghud2#34]
I would like the ability to have a shortcut on my desktop which could run the programs with set parameters to say set options or autostart the game with steam (like in the 1.4.0 release). With cmd options, it wouldn't get in the way whatsoever of users who wouldn't want to use them and give others the option of a one click start for MHUD2 and BoI with a .bat file or similar, along with other potential options.

**Comment by networkMe** [comment]
In the next version, one can use the command line to start Isaac Steam edition when MHUD2 runs.
See commit:
https://github.com/networkMe/missinghud2/commit/2d18fda4ae279b8d496f2483894f5b861abc0b88

Regarding setting options via cmdline, I don't see the need as they are saved in the .prefs file and really only need to be set once (on initial start-up).

**Comment by networkMe** [comment]
This is now present in v1.4.2 and above.
