### ISSUE TITLE
Greed Machine Jam Percentage

### ISSUE THREAD

**Issue by Ziboo** [networkMe/missinghud2#36]
Hi,

Thanks for this awesome mod ;)

Any chance to add the percentage chance for a character to jam the greed machine when you're in game and in the character selection screen ?

Thanks ;)

**Comment by networkMe** [comment]
I've had a think on this. The main reason I don't want to go ahead and add it, is that it's only useful for a time. Once you've filled the greed machine it essentially becomes a useless statistic. I feel the native implementation Nicalis has done is more than enough for the time it's relevant (even if I think it is slightly bugged right now).
