### ISSUE TITLE
Request: Build for Linux users

### ISSUE THREAD

**Issue by zakum42** [networkMe/missinghud2#37]
I'm trying to compile Missing HUD 2 in my Linux Desktop and I'm having some problems linking libraries. It would be good if a link with a compiled version for Linux users could be provided.

**Comment by networkMe** [comment]
Hey,

The reason you can't compile it is because the codebase is currently only compatible with Windows.
See below issue for more details:
https://github.com/networkMe/missinghud2/issues/23

Thanks,
