### ISSUE TITLE
enhancement : angel room %

### ISSUE THREAD

**Issue by RomainOdeval** [networkMe/missinghud2#4]
Hi !

Thanks for your great hud !

Just an idea : can you add an "Angel room"  chance % with these informations ?
http://platinumgod.co.uk/angel-room

Or maybe is useless ....

Thanks !

**Comment by networkMe** [comment]
This will be implemented in v1.4.0

See commit:
https://github.com/networkMe/missinghud2/commit/51f96837c58f65526963cd7e72285fe7bfdc508b

**Comment by networkMe** [comment]
v1.4.0 has been released with this feature.
