### ISSUE TITLE
Causes a crash when isaac updates

### ISSUE THREAD

**Issue by tom-churchill** [networkMe/missinghud2#40]
I was doing the Satoru Iwatas daily challenge and since isaac had updated and I was using an old version of missing hud, the game crashed. It would be good if when there is a new missing hud version it would notify you somehow. Even if it were to just close, then when you reopen it, you could see the new version message.

Anyway, good job on the Hud, its pretty nice.

**Comment by networkMe** [comment]
It does, when an update is available. Every time you open the main window.
I don't think a more intrusive update notification is necessary.

![MHUD2_Update_Photo](https://cloud.githubusercontent.com/assets/239436/11616859/cf260984-9cd5-11e5-90b5-939d966743be.png)

**Comment by tom-churchill** [comment]
Yeh a more intrusive notification is what I meant. I just leave missing hud running in the background, so the new version update rarely gets seen.
