### ISSUE TITLE
Request : Display Health

### ISSUE THREAD

**Issue by Judgy53** [networkMe/missinghud2#41]
Hi, I'd like to know if it would be possible plans on showing health ? I've looked in Cheat Engine tables and it seems they does get health (including soul hearts, etc.) fairly easily.

Bonus option : only display when health is normally hidden (Curse of the unknown for example), to not duplicate infos.

**Comment by networkMe** [comment]
You're right, it's easy. But, considering health (+ coins, keys and bombs) are all part of the native HUD I'm not sure how this is useful.

And if you have curse of the unknown, then you have curse of the unknown. The whole point is you cant see your health... MHUD2 has no association with cheating, and I'd like to keep it that way.
