### ISSUE TITLE
I don't know how to download the missing hud or how to even start it.

### ISSUE THREAD

**Issue by gr221051** [networkMe/missinghud2#48]
I have been trying to start the missing hud 2 but I don't know how. I have beeen trying to go to library>application support>steam>steamapps>common>the binding of isaac and put the folder there but it isn't working. I don't have a clue of how to start it or how to open it (if it is an app) please help!

**Comment by gr221051** [comment]
btw I am using a mac

**Comment by silasary** [comment]
Unfortunately, Missing HUD only supports the Windows version of the game.

**Comment by z96** [comment]
I believe the dev has said somewhere that he doesn't plan on developing the project on multiple operating systems.
Actually just found it.. https://github.com/networkMe/missinghud2/issues/23

**Comment by networkMe** [comment]
As others have said, MHUD2 is currently Windows only.

I'd also add that with the announcement of Afterbirth+ and official modding support, it is even more unlikely that I will ever port MHUD2. I'm 100% sure Nicalis will provide a way to implement an MHUD2 equivalent using Afterbirth+'s modding tools in a much friendlier way.
