### ISSUE TITLE
Show "not have enough ram" on win10 10586.29

### ISSUE THREAD

**Issue by darkness463** [networkMe/missinghud2#49]
This issue encounter after I upgread win10 to 10586. My computer has 16G ram and only 3G used when system showed the dialog told me OOM. When I play Afterbirth without missinghud2, this issue won't encounter(Maybe it will, because I didn't speed much time to play without missinghud2).

**Comment by networkMe** [comment]
I would be extremely surprised if MHUD2 is actually causing this as it uses such little memory (high performance was one of it's main design principles to avoid dropping FPS). However, I will leave this open until you or I can confirm it.

**Comment by darkness463** [comment]
I think it is not caused by MHUD2 because the OOM dialog showed yestoday while I was not playing issac. Maybe it's caused by my settings of virtual memory. Sorry. T_T

**Comment by networkMe** [comment]
Thanks for letting me know, I didn't think it was MHUD but it's good of you to confirm it :)
