### ISSUE TITLE
Error while executing LoadLibraryA in the Bol process

### ISSUE THREAD

**Issue by victorheld** [networkMe/missinghud2#5]
[screenshot](https://i.imgur.com/uRy2vjO.png)

**Comment by 40163650** [comment]
I may not be a developer on this project but here are a few things to consider:
Could you provide some more information? (OS, version, etc.)
Have you got all the files (in the same location)?
Have you tried getting the latest version and running that?
Has it ever worked for you or is it the first time you tried using missingHUD?

**Comment by victorheld** [comment]
@40163650 Oh yeah sorry,
I'm using the latest version of isaac and missingHUD(Also tried some different versions)
OS: Windows 10 x64

**Comment by victorheld** [comment]
I think i found the problem it works if i put the .exe in the same directory as isaac-ng.exe.

I do not know if it is intended to be used this way because the description states: "You simply run the main executable (which acts as the DLL injector) and the HUD will be drawn onto an active Rebirth process." 

If it is intended that you put the .exe in the isaac directory i wil close this issue.(Maybe update the description in this case)

**Comment by 40163650** [comment]
I think so.

**Comment by victorheld** [comment]
Ok I will close the issue for now.

**Comment by networkMe** [comment]
Can you tell me the exact directory path you were running it from before you moved it to your Isaac directory?
I have a feeling it had some unicode characters or something in it that LoadLibraryA doesn't like. But it would be nice to know as I might be able to fix it (probably not).

To answer your question though; you should be able to run it from anywhere you please, it shouldn't need to be in your Isaac directory.

**Comment by victorheld** [comment]
@networkMe That could indeed be the issue the directory I was running it from has spaces(ALT + 255) in the name: "C:\Users\victo\Desktop\        \Isaac Custom hud"

**Comment by networkMe** [comment]
Yep, that's indeed the issue. ALT + 255 is a unicode character and LoadLibrary only supports standard characters.

I could change it to use LoadLibraryW but I'm not going to as it's a fair bit of work. What I will do is make a better error message so people can avoid characters like that in their path.

Thanks

**Comment by Rifdos** [comment]
@networkMe  I've got the same problem    but I don't know where to put in each file

**Comment by networkMe** [comment]
This is an old issue that no longer applies (you can now have unicode characters in your path).

The error though, can still remain, and it's due to something blocking DLL injection. Usually an anti-virus. Running MHUD2 as admin may fix it, it may not.
