### ISSUE TITLE
It works on MAC?

### ISSUE THREAD

**Issue by RuisuSato** [networkMe/missinghud2#50]
Just wanna know if it's work on MAC

**Comment by silasary** [comment]
Nope. Windows only.

**Comment by Thowo91** [comment]
I would like to see this mod working on Linux !
Any Change to get that ?

**Comment by silasary** [comment]
The method MissingHUD hooks into the game is Windows specific (DLL
Injection).
A decent chunk of the codebase would have to be completely rewritten to
support Linux.
So no, it's still Windows only.
