### ISSUE TITLE
Enhancement: Optional item tracker

### ISSUE THREAD

**Issue by joshizpro** [networkMe/missinghud2#7]
Really impressed with your work on this program, a suggestion would be to add a simple overlay for items picked up each run, as far as I can see the overlay system you are using would be perfect, I would love if it was written in c# so I could work on it but I have no experience in C++. Also enable/disable with a key for people who don't want to see it would be good too. Thanks for such a helpful program man.

**Comment by networkMe** [comment]
I considered this when I first started Missing HUD 2 but Hyphen-ated's Item Tracker already does this really well. https://github.com/Hyphen-ated/RebirthItemTracker

In addition, it looks like Afterbirth is going to have a native implementation of an item tracker (from the photos at least).

**Comment by joshizpro** [comment]
Do you know of any that actually overlay the game, because I downloaded it and unless I'm doing something wrong it's not actually showing over the game in fullscreen like your HUD. Do you have a steam account I could contact you on to talk more about it?

**Comment by networkMe** [comment]
No, it doesn't directly overlay, you're right.
But Afterbirth is getting what you're requesting in-built:
http://i.imgur.com/TzTlKSL.png

So, there's very little point in implementing it into MHUD2.

**Comment by joshizpro** [comment]
If you add me on steam maybe we could talk about having it implemented in MissinHUD2 for a price? I really want built in item tracking and really don't want to wait for Afterbirth, I've managed to make a c# program to track items but it's very much similar to the one you linked me, external, not overlayed

**Comment by networkMe** [comment]
Sorry, I have no interest in implementing something that Afterbirth will have by default, there's very little point to it. Having said that, feel free to clone the source code and work on it yourself. A lot of the code you need is already implemented (like the sprite-sheet renderer).
