### ISSUE TITLE
1.2.4 does not load at all.

### ISSUE THREAD

**Issue by Centopus** [networkMe/missinghud2#9]
Hello

1.2.3 works fine.

http://i.imgur.com/Dxgm4g6.png

Does not produce any logs. 

Win7x64. Antivirus and firewall do not interfere (checked).

If there's any other information I can provide, please ask.

**Comment by adods** [comment]
Got the same problem. but 1.2.3 works well. I'm using Windows 10

**Comment by networkMe** [comment]
Can either of you tell me if this revision crashes for you?
And if it does, does it have a log at all?
https://mega.nz/#!d5gjABqB!X6twWgCxCEi9i2YPSvZNuzrCicgFrVUaYJLSRduNcJ4

**Comment by Centopus** [comment]
Hello

This one works. Thnx.

**Comment by networkMe** [comment]
Thanks!

I will make sure this patch gets put in Afterbirth's version (it affects very few people)
